package com.bezzangss.sign.common.exception;

import lombok.Getter;

@Getter
public enum ErrorCode {
    BAD_REQUEST(400_00_00, "잘못된 요청."),

    INTERNAL_SERVER_ERROR(500_00_00, "서버 내부 오류."),

    /**
     * COMMON
     */
    NOT_FOUND_ARGUMENT_EXCEPTION(400_00_01, "인자가 존재하지 않습니다."),
    ILLEGAL_ARGUMENT_EXCEPTION(400_00_02, "인자가 부적합합니다."),
    BIND_EXCEPTION(400_00_03, "데이터 바인딩 실패."),
    JSON_PROCESSING_EXCEPTION(400_00_04, "JSON 처리 실패."),
    HTTP_MESSAGE_NOT_READABLE_EXCEPTION(400_00_10, "HTTP 메시지 읽기 실패."),

    /**
     * STORAGE
     */
    STORAGE_ILLEGAL_TYPE_INTERNAL_SERVER_ERROR(500_10_20, "타입이 부적합합니다."),

    /**
     * RESOURCE
     */
    RESOURCE_NOT_FOUND_EXCEPTION(404_11_00, "정보가 존재하지 않습니다."),

    RESOURCE_WRITE_INTERNAL_SERVER_ERROR(500_11_11, "리소스 쓰기 실패."),
    RESOURCE_ILLEGAL_INTERNAL_SERVER_ERROR(500_11_20, "타입이 부적합합니다."),

    /**
     * RESOURCE_REFERENCE
     */
    RESOURCE_REFERENCE_NOT_FOUND_EXCEPTION(404_12_00, "정보가 존재하지 않습니다."),

    RESOURCE_REFERENCE_ILLEGAL_TYPE_INTERNAL_SERVER_ERROR(500_12_20, "타입이 부적합합니다."),

    /**
     * BASE_DOCUMENT
     */
    BASE_DOCUMENT_ILLEGAL_TYPE_EXCEPTION(400_20_20, "타입이 부적합합니다."),

    BASE_DOCUMENT_NOT_FOUND_EXCEPTION(404_20_00, "정보가 존재하지 않습니다."),

    /**
     * TEMPLATE_DOCUMENT
     */
    TEMPLATE_DOCUMENT_STATUS_IS_NONE_EXCEPTION(400_21_21, "NONE 상태입니다."),
    TEMPLATE_DOCUMENT_STATUS_IS_DELETED_EXCEPTION(400_21_22, "DELETE 상태입니다."),
    TEMPLATE_DOCUMENT_IS_NOT_UPDATABLE_EXCEPTION(400_21_31, "변경할 수 없는 상태입니다."),
    TEMPLATE_DOCUMENT_NOT_FOUND_EXCEPTION(404_21_00, "정보가 존재하지 않습니다."),

    /**
     * DOCUMENT
     */
    DOCUMENT_STATUS_IS_NOT_NONE_EXCEPTION(400_30_11, "NONE 상태가 아닙니다."),
    DOCUMENT_STATUS_IS_NOT_PROCESSING_EXCEPTION(400_30_12, "PROCESSING 상태가 아닙니다."),
    DOCUMENT_STATUS_IS_NOT_COMPLETED_EXCEPTION(400_30_13, "COMPLETED 상태가 아닙니다."),
    DOCUMENT_STATUS_IS_NOT_DELETED_EXCEPTION(400_30_14, "DELETED 상태가 아닙니다."),

    DOCUMENT_STATUS_IS_NONE_EXCEPTION(400_30_21, "NONE 상태입니다."),
    DOCUMENT_STATUS_IS_PROCESSING_EXCEPTION(400_30_22, "PROCESSING 상태입니다."),
    DOCUMENT_STATUS_IS_COMPLETED_EXCEPTION(400_30_23, "COMPLETED 상태입니다."),
    DOCUMENT_STATUS_IS_DELETED_EXCEPTION(400_30_24, "DELETED 상태입니다."),

    DOCUMENT_NOT_FOUND_EXCEPTION(404_30_00, "정보가 존재하지 않습니다."),
    DOCUMENT_EXISTS_EXCEPTION(409_30_00, "정보가 이미 존재합니다."),

    /**
     * STANDARD_DOCUMENT
     */
    STANDARD_DOCUMENT_NOT_FOUND_EXCEPTION(404_31_00, "정보가 존재하지 않습니다."),
    STANDARD_DOCUMENT_EXISTS_EXCEPTION(409_31_00, "정보가 이미 존재합니다."),

    /**
     * PUBLISHER
     */
    PUBLISHER_NOT_FOUND_EXCEPTION(404_41_00, "정보가 존재하지 않습니다."),
    PUBLISHER_EXISTS_EXCEPTION(409_41_00, "정보가 이미 존재합니다."),

    /**
     * SIGNER
     */
    SIGNER_STATUS_IS_NOT_NONE_EXCEPTION(400_42_11, "NONE 상태가 아닙니다."),
    SIGNER_STATUS_IS_NOT_WAITING_EXCEPTION(400_42_12, "WAITING 상태가 아닙니다."),
    SIGNER_STATUS_IS_NOT_READY_EXCEPTION(400_42_13, "READY 상태가 아닙니다."),
    SIGNER_STATUS_IS_NOT_SIGNED_EXCEPTION(400_42_14, "SIGNED 상태가 아닙니다."),

    SIGNER_STATUS_IS_NONE_EXCEPTION(400_42_21, "NONE 상태입니다."),
    SIGNER_STATUS_IS_WAITING_EXCEPTION(400_42_22, "WAITING 상태입니다."),
    SIGNER_STATUS_IS_READY_EXCEPTION(400_42_23, "READY 상태입니다."),
    SIGNER_STATUS_IS_SIGNED_EXCEPTION(400_42_24, "SIGNED 상태입니다."),

    SIGNER_IS_NOT_IN_ORDER_EXCEPTION(400_42_31, "서명 순서가 아닙니다."),

    SIGNER_NOT_FOUND_EXCEPTION(404_42_00, "정보가 존재하지 않습니다."),
    SIGNER_NONE_NOT_FOUND_EXCEPTION(404_42_01, "NONE 서명자가 존재하지 않습니다."),
    SIGNER_WAITING_NOT_FOUND_EXCEPTION(404_42_02, "WAITING 서명자가 존재하지 않습니다."),
    SIGNER_READY_NOT_FOUND_EXCEPTION(404_42_03, "READY 서명자가 존재하지 않습니다."),
    SIGNER_SIGNED_NOT_FOUND_EXCEPTION(404_42_04, "SIGNED 서명자가 존재하지 않습니다."),

    SIGNER_EXISTS_EXCEPTION(409_42_00, "정보가 이미 존재합니다."),

    SIGNER_ILLEGAL_INTERNAL_SERVER_ERROR(500_42_00, "서명자 정보가 부적합합니다."),

    /**
     * CC
     */
    CC_NOT_FOUND_EXCEPTION(404_43_00, "정보가 존재하지 않습니다."),
    CC_EXISTS_EXCEPTION(409_43_00, "정보가 이미 존재합니다."),

    ;

    private final int code;
    private final String message;

    ErrorCode(int code, String message) {
        this.code = code;
        this.message = message;
    }
}
